spring:
  application:
    name: starandcar
  web:
    resources:
      static-locations: file:/home/nkrishnawat/uploads/,classpath:/static/,classpath:/public/
    mvc:
      static-path-pattern: /uploads/**
  datasource:
    url: jdbc:mariadb://localhost:3206/starandcardb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
file:
  upload-dir: /home/nkrishnawat/uploads